{
 "title": "myorg_dashboad",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Online users per course",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT  count(user_id) FROM myorg_topic2  group by course_id"
    }
   ]
  },
  {
   "title": "number of clicks in each part",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(*) FROM myorg_topic2 group by event_place"
    }
   ]
  },
  {
   "title": "online users every minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT count(DISTINCT(user_id)) FROM myorg_topic  GROUP BY time(1m)\n"
    }
   ]
  }
 ]
}