version: "3.7"

volumes:
    grafana_data:
    prometheus_data:
    grafana_provisioning:
    influxdb-storage:

services:
  grafana:
    image: docker.repos.balad.ir/grafana/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=project_admin
      - GF_SECURITY_ADMIN_PASSWORD=sample_pass
      - GF_SECURITY_ALLOW_EMBEDDING=true
      # - GF_SECURITY_COOKIE_SAMESITE=disabled
    #   - GF_RENDERING_SERVER_URL=http://renderer:8081/render
    #   - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    #   - GF_LOG_FILTERS=rendering:debug
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana.ini:/etc/conf/custom.ini
      - grafana_provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards 
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - renderer
      - influxdb

  influxdb:
    image: docker.repos.balad.ir/influxdb:1.8.10
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./conf/setup_influxdb.sh:/docker-entrypoint-initdb.d/setup.sh:ro
    environment:
      - INFLUXDB_DB=myorg
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
networks:
  default:
    name: cassandra_out_net
    external: true