version: "3.7"

volumes:
    grafana_data:
    prometheus_data:
    grafana_provisioning:
    influxdb-storage:

# networks:
#   monitoring_network:

services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=project_admin
      - GF_SECURITY_ADMIN_PASSWORD=sample_pass
    #   - GF_RENDERING_SERVER_URL=http://renderer:8081/render
    #   - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    #   - GF_LOG_FILTERS=rendering:debug
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana.ini:/etc/conf/custom.ini
      - grafana_provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards 
    ports:
      - 3000:3000
    # networks:
    #   - monitoring_network
    depends_on:
      - prometheus
      - renderer
      - influxdb

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    # networks:
    #   - monitoring_network
    environment:
      ENABLE_METRICS: 'true'

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    user: root
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./conf/web.yml:/etc/prometheus/web.yml
      - prometheus_data:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.config.file=/etc/prometheus/web.yml'
    ports:
      - 9090:9090
    # networks:
    #   - monitoring_network
     
  # postgres_db:
  #   image: postgres:13.0
  #   ports:
  #     - 5432:5432
  #   networks:
  #   - monitoring_network
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: example

  influxdb:
    # image: influxdb:latest
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    # networks:
    #   - monitoring_network
  
networks:
  default:
    name: monitoring_network