version: "3"
services:
  server:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./:/home/app/server
      - /home/app/server/target
      - /home/app/server/project
    networks:
      - cassandra
      - app

  redis-db:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - app

volumes:
  cache:

networks:
  app:
    name: app_out_net
  cassandra:
    name: cassandra_app_out_net