version: '3'
services:
  cassandra1:
    image: docker.repos.balad.ir/cassandra:3.11.2
    ports:
      - "7001:7000"
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - cassandra_data1:/var/lib/cassandra
      - cassandra_log1:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: docker.repos.balad.ir/cassandra:3.11.2
    ports:
      - "7002:7000"
      - "9043:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - cassandra_data2:/var/lib/cassandra
      - cassandra_log2:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M

  cassandra-load-keyspace:
    image: docker.repos.balad.ir/cassandra:3.11.2
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
    volumes:
      - ./schema.cql:/scripts/schema.cql
    command: /bin/bash -c "cqlsh -u cassandra -p cassandra -f /scripts/schema.cql cassandra1"
    
volumes:
  cassandra_data2:
  cassandra_data1:
  cassandra_log1:
  cassandra_log2:

networks:
  default:
    name: cassandra_out_net