version: '2.2'
services:
  cassandra1:
    image: cassandra:3.11.2
    ports:
      - "7001:7000"
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra1:/var/lib/cassandra
      - ./logs/cassandra1:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: cassandra:3.11.2
    ports:
      - "7002:7000"
      - "9043:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra2:/var/lib/cassandra
      - ./logs/cassandra2:/var/log/cassandra
      - ./schema.cql:/scripts/schema.cql
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra-load-keyspace:
    image: cassandra:3.11.2
    depends_on:
      cassandra1:
        condition: service_healthy
      cassandra2:
        condition: service_healthy
    volumes:
      - ./schema.cql:/scripts/schema.cql
    command: /bin/bash -c "cqlsh -u cassandra -p cassandra -f /scripts/schema.cql cassandra1"

